export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'//This Runs On success
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const CLEAR_PROFILE='CLEAR_PROFILE'
export const LOGOUT = 'LOGOUT'
export const GET_BLOG = "GET_BLOG";
export const BLOG_ERROR = "BLOG_ERROR";
export const CLEAR_BLOG = "CLEAR_BLOG";
export const UPDATE_BLOG =   'UPDATE_BLOG';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const GET_BLOGS = 'GET_BLOGS'
export const GET_REPOS = 'GET_REPOS'
export const GET_POSTS = 'GET_POSTS'
export const POST_ERROR = 'POST_ERROR'
export const UPDATE_LIKES = 'UPDATE_LIKES'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST'
export const GET_POST = 'GET_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'